name: Curse
main: me.hgilman.Curse.Curse
version: 0.5
commands:
   curse:
      description: Makes the player's life... unpleasant.
      permission: curse.curse
      permission-message: ""
      usage: /<command> <player>
